# Generated by Django 6.0.2 on 2026-04-06 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='is_active',
        ),
    ]
