# Generated by Django 6.0.2 on 2026-03-31 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookshelf_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='is_rented',
            field=models.BooleanField(default=False, verbose_name='貸出可'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookshelf_name', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Stocks', to='libraryapp.bookshelf')),
                ('isbn', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Stocks', to='libraryapp.book')),
            ],
        ),
    ]
