# Generated by Django 6.0.2 on 2026-04-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0002_remove_reservation_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
