# Generated by Django 6.0.2 on 2026-04-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_remove_stock_is_reserved_alter_borrow_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holdstock',
            name='reserved_from',
        ),
    ]
