# Generated by Django 6.0.2 on 2026-06-03 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0009_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover_image',
            new_name='cover_url',
        ),
    ]
