# Generated by Django 6.0.2 on 2026-06-16 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0010_rename_cover_image_book_cover_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holdstock',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hold', to='libraryapp.stock'),
        ),
    ]
