# Generated by Django 6.0.2 on 2026-06-25 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0011_alter_holdstock_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['due_date']},
        ),
    ]
