# Generated by Django 6.0.2 on 2026-07-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0012_alter_borrow_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='ISBN-10 または ISBN-13（ハイフン可）', max_length=20, unique=True, verbose_name='ISBN'),
        ),
    ]
